# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 786442f32c425f6e51e0e37358544ef6ff43672684b939ba22e6b9b666ab235f5b6b354d4263c534a106cfea49e76dea33a280c05470e0d12e07fc2c77cbc8fe

test:
  secret_key_base: 9d908fea1f6c5ab41d6bcbc092c8dfa4d0c089ed9269b9f395725e660e163b9d0cd59acd095eb400acd0cb05f8a86c6f5c840491f754df7d184d282743742892

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
